const compounds=[
{name:"Retatrutide",cat:"metabolic",label:"Metabolic research",desc:"A research-stage multi-receptor agonist studied in metabolic and obesity research.",body:"Retatrutide is an investigational peptide agonist with activity at GIP, GLP-1, and glucagon receptors. Published clinical research has examined its effects in obesity and metabolic disease. It is not presented here as a treatment recommendation or a guide for self-use."},
{name:"Tirzepatide",cat:"metabolic",label:"Metabolic research",desc:"A dual GIP/GLP-1 receptor agonist studied extensively in metabolic research.",body:"Tirzepatide is a GIP and GLP-1 receptor agonist. Its pharmacology and clinical evidence are distinct from research-only materials sold by laboratory suppliers. This page is for scientific context only and does not provide dosing or medical-use instructions."},
{name:"Semaglutide",cat:"metabolic",label:"Metabolic research",desc:"A GLP-1 receptor agonist widely studied in glucose regulation and obesity.",body:"Semaglutide is a GLP-1 receptor agonist with substantial published clinical literature. Regulatory status depends on the specific approved drug product and indication; a research chemical bearing the same compound name should not be assumed equivalent to an approved medicine."},
{name:"Tesamorelin",cat:"endocrine",label:"Endocrine research",desc:"A growth-hormone-releasing-hormone analogue studied in endocrine physiology.",body:"Tesamorelin is an analogue of growth-hormone-releasing hormone. Research examines its interaction with the GH/IGF-1 axis. This educational summary does not provide administration, dosing, or individualized medical guidance."},
{name:"BPC-157",cat:"recovery",label:"Tissue research",desc:"An experimental peptide discussed in preclinical tissue and gastrointestinal research.",body:"BPC-157 appears primarily in preclinical literature. Claims online often go beyond the quality of available human evidence. When evaluating it, distinguish animal or cell findings from demonstrated human clinical outcomes."},
{name:"TB-500 / Thymosin β4 research",cat:"recovery",label:"Tissue research",desc:"Research terminology often used around thymosin beta-4 related materials.",body:"Thymosin beta-4 is a naturally occurring peptide studied in cell migration and tissue biology. Products marketed as TB-500 require careful evaluation because naming, composition, and evidence may not map neatly onto the endogenous peptide literature."},
{name:"CJC-1295",cat:"endocrine",label:"Endocrine research",desc:"A synthetic GHRH analogue investigated for effects on growth-hormone signaling.",body:"CJC-1295 is a synthetic analogue related to growth-hormone-releasing hormone research. Different forms and naming conventions can create confusion, making exact compound identity especially important when reading studies or analytical reports."},
{name:"Ipamorelin",cat:"endocrine",label:"Endocrine research",desc:"A growth-hormone secretagogue used in experimental endocrine research.",body:"Ipamorelin is studied as a ghrelin-receptor agonist and growth-hormone secretagogue. Online claims should be separated from controlled evidence, and research-product documentation should not be treated as proof of clinical safety."},
{name:"Semax",cat:"neuro",label:"Neuroscience",desc:"A synthetic peptide studied in neuroscience research, with much of the literature originating outside the U.S.",body:"Semax has been investigated in neuroscience contexts. Evidence quality, regulatory status, and clinical adoption vary by country. AIM does not interpret that research as a recommendation for personal use."},
{name:"Selank",cat:"neuro",label:"Neuroscience",desc:"A synthetic peptide investigated in experimental neurobehavioral research.",body:"Selank appears in experimental literature related to neurobehavioral effects. Readers should examine study design, replication, sample size, and regulatory context rather than relying on marketing summaries."}
];
const cards=document.getElementById("cards"),search=document.getElementById("search"),count=document.getElementById("count");let filter="all";
function render(){let q=search.value.toLowerCase();let x=compounds.filter(c=>(filter==="all"||c.cat===filter)&&(c.name+" "+c.label+" "+c.desc).toLowerCase().includes(q));count.textContent=x.length+" topics";cards.innerHTML=x.map(c=>`<article class="card"><span class="tag">${c.label}</span><h3>${c.name}</h3><p>${c.desc}</p><button onclick="openTopic('${c.name.replaceAll("'","\\'")}')">Read research overview →</button></article>`).join("")||"<p>No topics match that search.</p>"}
search.oninput=render;document.querySelectorAll("#filters button").forEach(b=>b.onclick=()=>{document.querySelectorAll("#filters button").forEach(x=>x.classList.remove("active"));b.classList.add("active");filter=b.dataset.filter;render()});
function openTopic(n){let c=compounds.find(x=>x.name===n);document.getElementById("modalContent").innerHTML=`<span class="tag">${c.label}</span><h2>${c.name}</h2><p>${c.body}</p><div class="notice"><b>Research-information notice:</b> This page is educational only and does not provide medical advice, dosing, reconstitution, injection, or treatment instructions.</div>`;document.getElementById("modal").classList.add("show");document.body.style.overflow="hidden"}
function close(){document.getElementById("modal").classList.remove("show");document.body.style.overflow=""}document.getElementById("close").onclick=close;document.getElementById("modal").onclick=e=>{if(e.target.id==="modal")close()};document.addEventListener("keydown",e=>{if(e.key==="Escape")close()});document.getElementById("menu").onclick=()=>document.querySelector(".nav").classList.toggle("open");document.querySelectorAll(".nav a").forEach(a=>a.onclick=()=>document.querySelector(".nav").classList.remove("open"));render();