const products=[{"name": "Retatrutide", "cat": "Metabolic", "desc": "Triple GIP/GLP-1/glucagon receptor agonist", "page": "compounds/retatrutide.html"}, {"name": "Tirzepatide", "cat": "Metabolic", "desc": "Dual GIP/GLP-1 receptor agonist", "page": "compounds/tirzepatide.html"}, {"name": "Semaglutide", "cat": "Metabolic", "desc": "GLP-1 receptor agonist", "page": "compounds/semaglutide.html"}, {"name": "Tesamorelin", "cat": "Endocrine", "desc": "GHRH analogue", "page": "compounds/tesamorelin.html"}, {"name": "BPC-157", "cat": "Tissue", "desc": "Experimental pentadecapeptide", "page": "compounds/bpc-157.html"}, {"name": "TB-500 / Thymosin \u03b24", "cat": "Tissue", "desc": "Thymosin-related research material", "page": "compounds/tb-500-thymosin-4.html"}, {"name": "MOTS-c", "cat": "Mitochondrial", "desc": "Mitochondrial-derived peptide", "page": "compounds/mots-c.html"}, {"name": "SS-31 / Elamipretide", "cat": "Mitochondrial", "desc": "Mitochondrial-targeted tetrapeptide", "page": "compounds/ss-31-elamipretide.html"}, {"name": "GHK-Cu", "cat": "Tissue", "desc": "Copper tripeptide", "page": "compounds/ghk-cu.html"}, {"name": "KPV", "cat": "Tissue", "desc": "Alpha-MSH-derived tripeptide", "page": "compounds/kpv.html"}, {"name": "Semax", "cat": "Neuroscience", "desc": "ACTH-fragment-derived research peptide", "page": "compounds/semax.html"}, {"name": "Selank", "cat": "Neuroscience", "desc": "Tuftsin-analogue heptapeptide", "page": "compounds/selank.html"}, {"name": "DSIP", "cat": "Neuroscience", "desc": "Delta sleep-inducing peptide", "page": "compounds/dsip.html"}, {"name": "Epithalon", "cat": "Aging research", "desc": "Pineal tetrapeptide", "page": "compounds/epithalon.html"}, {"name": "AOD9604", "cat": "Metabolic", "desc": "Modified hGH fragment 176-191", "page": "compounds/aod9604.html"}, {"name": "5-Amino-1MQ", "cat": "Metabolic", "desc": "NNMT inhibitor research compound", "page": "compounds/5-amino-1mq.html"}, {"name": "NAD+", "cat": "Cellular metabolism", "desc": "Nicotinamide adenine dinucleotide", "page": "compounds/nad.html"}, {"name": "Adamax", "cat": "Neuroscience", "desc": "Research peptide", "page": "compounds/adamax.html"}, {"name": "CJC-1295 + Ipamorelin", "cat": "Endocrine", "desc": "GHRH analogue + ghrelin-receptor agonist blend", "page": "compounds/cjc-1295-ipamorelin.html"}, {"name": "GLOW Blend", "cat": "Blend", "desc": "GHK-Cu / BPC-157 / thymosin-related blend", "page": "compounds/glow-blend.html"}];
const grid=document.getElementById('grid'),search=document.getElementById('search'),count=document.getElementById('count'),filters=document.getElementById('filters');let active='All';
const cats=['All',...new Set(products.map(x=>x.cat))];filters.innerHTML=cats.map((c,i)=>`<button class="${i?'':'active'}" data-cat="${c}">${c}</button>`).join('');
function render(){let q=search.value.toLowerCase();let rows=products.filter(x=>(active==='All'||x.cat===active)&&(x.name+' '+x.cat+' '+x.desc).toLowerCase().includes(q));count.textContent=rows.length+' research pages';grid.innerHTML=rows.map(x=>`<article class="card"><span class="tag">${x.cat}</span><h3>${x.name}</h3><p>${x.desc}</p><div class="links"><a class="study" href="${x.page}">Open research page →</a></div></article>`).join('')}
search.oninput=render;filters.onclick=e=>{if(e.target.tagName!=='BUTTON')return;active=e.target.dataset.cat;filters.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b===e.target));render()};render();

// Supabase connection
const SUPABASE_URL = "https://mkxhosiptmmhotlqcqpy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_dvVyamZ5BKFopo_O2nC3EA_VaHxHEbA";

const supabaseClient = window.supabase.createClient(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY
);
